{
 "title": "Fabric Monitoring (SNMP)",
 "description": "Monitor IP Fabric built with EVPN/VXLAN Jumpstart project",
 "tags": [
  "evpn",
  "junos",
  "snmp"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "HOSTNAME",
    "label": "Device Hostname",
    "query": "SHOW TAG VALUES FROM \"snmp_BGP\" with KEY = \"hostname\""
   },
   {
    "name": "ifName",
    "label": "Interface name",
    "query": "SHOW TAG VALUES FROM \"snmp_interfaces_statistics\" with KEY = \"ifName\""
   },
   {
    "name": "neighbors",
    "label": "Peer",
    "query": "SHOW TAG VALUES FROM \"snmp_bgp_statistics\" with KEY = \"bgpPeerRemoteAddr\""
   }
  ]
 },
 "panels": [
  {
   "title": "BGP Peer states",
   "type": "table",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 0 },
   "repeat": "HOSTNAME",
   "targets": [
    {
     "alias": "$HOSTNAME - connection to $tag_bgpPeerRemoteAddr - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_bgp_statistics",
     "select": [
      [
       { "params": [ "bgpPeerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$neighbors$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Update messages for $HOSTNAME",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "repeat": "HOSTNAME",
   "yaxes": [
    { "format": "ops", "label": "# of Update messages" }
   ],
   "targets": [
    {
     "alias": "$tag_bgpPeerRemoteAddr - Update $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "bgpPeerRemoteAddr" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp_bgp_statistics",
     "select": [
      [
       { "params": [ "bgpPeerInUpdates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "IN" ], "type": "alias" }
      ],
      [
       { "params": [ "bgpPeerOutUpdates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ "OUT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "bgpPeerRemoteAddr", "operator": "=~", "value": "/^$neighbors$/" }
     ]
    }
   ]
  },
  {
   "title": "BGP Update messages for $HOSTNAME",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "# of Update messages" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "inetCidrRouteProto" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp_routing_statistics",
     "select": [
      [
       { "params": [ "inetCidrRouteType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics for $HOSTNAME (bps)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "repeat": "HOSTNAME",
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "ingress" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "egress" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Statistics $HOSTNAME (pps)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "repeat": "HOSTNAME",
   "targets": [
    {
     "alias": "$tag_ifName - $col (pps)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "ingress" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "egress" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HOSTNAME - IN/OUT bps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "repeat": "HOSTNAME",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Ingress" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Egress" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  },
  {
   "title": "$HOSTNAME - IN/OUT pps",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "repeat": "HOSTNAME",
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "snmp_interfaces_statistics",
     "select": [
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Ingress" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Egress" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "=~", "value": "/^$HOSTNAME$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$ifName$/" }
     ]
    }
   ]
  }
 ]
}